### ISSUE TITLE
requests.exceptions.ConnectionError: Expected status code 200, but got 401

### ISSUE THREAD

**Issue by mcgeo52** [gregmccoy/sproutvideo-python#2]
I am using the following code:
````
#!python
import sprout
from sprout.client import SproutClient
from sprout.video import Video

sprout = SproutClient("TOKEN")

vidPath = '/home/ec2-user/renders/proj005/0001.m4v'

#Upload video
response = sprout.video.upload(vidPath, title="Test 1")
````

I get the following error:
`[ec2-user@ip-172-31-1-228 ~]$ python3 sprout-upload-test.py
Traceback (most recent call last):
  File "sprout-upload-test.py", line 11, in <module>
    response = sprout.video.upload(vidPath, title="Test 1")
  File "/home/ec2-user/sprout/video.py", line 64, in upload
    return self.client.call_api("https://api.sproutvideo.com/v1/videos", "POST", data=data, files=files)
  File "/home/ec2-user/sprout/client.py", line 41, in call_api
    raise requests.ConnectionError("Expected status code 200, but got {}".format(response.status_code))
requests.exceptions.ConnectionError: Expected status code 200, but got 401
`

I believe this is because I am not passing the id to sprout to generate the pass token. How do I pass info to sprout to generate the token? This is not being run from within a web page.

**Comment by mcgeo52** [comment]
Replacing "TOKEN" with the SproutVideo API key (In quotes) was the answer. Duh!
